language: node_js

node_js:
  - "lts/*"
  - "10"
  - "8"

cache: npm

script:
  - npm run lint
  - npm run cover

after_success:
  - npm install codecov
  - npm run codecov

notifications:
  email:
    on_success: change
    on_failure: always
